### ISSUE TITLE
The question about  fusing smooth factor for the model used GQA/MQA.

### ISSUE THREAD

**Issue by shhn1** [mit-han-lab/deepcompressor#11]
Thank you for your great work!

I had a question when using the lmquant quantization model. The paper proposed to fuse the smooth factor of the `attn-out` layer into the weight of `v_proj` when using the SmoothQuant. But I found that for models like qwen2 that use GQA/MQA, the smooth factor cannot be fused since the smoother obtained by the activation of `attn-out` does not match the weight shape of `v_proj`. Do you have any suitable solution for this problem?

Looking forward to your reply :）

**Comment by synxlin** [comment]
Hi,
We do support fusing smooth factor for models with GQA/MQA. In [`smooth_attention`](https://github.com/mit-han-lab/deepcompressor/blob/main/deepcompressor/calib/smooth.py#L1031) function, we provide an argument called `num_head_repeats`. If a model uses GQA with 32 attention heads and 8 kv heads, you can parse the argument with `num_head_repeats=4`, so that [`SmoothCalibrator`](https://github.com/mit-han-lab/deepcompressor/blob/main/deepcompressor/calib/smooth.py#L1031) will take care of smooth factor (see code [here](https://github.com/mit-han-lab/deepcompressor/blob/main/deepcompressor/calib/smooth.py#L1031)).
